#!/bin/sh
set -x

switch=virbr0

if [ -n "$1" ];then
        /usr/bin/sudo tunctl -u `whoami` -t $1
        /usr/bin/sudo ip link set $1 up
        sleep 0.5s
        /usr/bin/sudo brctl addif $switch $1
        exit 0
else
        echo "Error: no interface specified"
        exit 1
fi
